// Runs in an isolated shadow root so existing website styles and forms stay intact.
export function chatClient(){
 if(document.getElementById('nds-live-chat'))return;
 const host=document.createElement('div');host.id='nds-live-chat';document.body.append(host);const root=host.attachShadow({mode:'open'});
 root.innerHTML=`<style>
 :host{position:fixed;left:20px;bottom:20px;z-index:2147483000;font:14px/1.5 system-ui,Arial;color:#153052}*{box-sizing:border-box}button,input,textarea,a{font:inherit}button,a{cursor:pointer}button{border:0;border-radius:10px;padding:11px 14px;font-weight:650;background:#1d56d8;color:#fff}button:disabled{opacity:.65;cursor:wait}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #66a9ff;outline-offset:2px}#launcher{box-shadow:0 6px 24px #102d4a40;border:1px solid #fff}#panel{position:absolute;bottom:60px;left:0;width:380px;max-width:calc(100vw - 40px);height:570px;max-height:calc(100dvh - 110px);background:#fff;border:1px solid #d6e1ef;border-radius:18px;box-shadow:0 15px 60px #102d4a40;overflow:hidden;display:flex;flex-direction:column}[hidden]{display:none!important}header{background:#102d4a;color:#fff;padding:15px 18px;display:flex;gap:10px;align-items:center;flex-shrink:0}header strong{font-size:16px}header small{display:block;color:#c7d6eb}header button{margin-left:auto;background:transparent;font-size:22px;padding:0 8px}#start{padding:20px;overflow:auto}h2{font-size:20px;margin:0 0 8px}p{margin:8px 0 16px}label{display:block;font-weight:600;margin:12px 0 5px}input,textarea{display:block;width:100%;min-width:0;border:1px solid #bccbdd;border-radius:9px;padding:10px;background:#fff;color:#153052}textarea{resize:vertical;min-height:75px}#start button{width:100%;margin-top:15px}.small{font-size:12px;color:#5c718c}#conversation{min-height:0;flex:1;display:flex;flex-direction:column}#messages{overflow:auto;flex:1;padding:15px;overscroll-behavior:contain}.msg{white-space:pre-wrap;overflow-wrap:anywhere;border-radius:12px;background:#edf3fa;margin:0 18px 12px 0;padding:11px 13px}.msg.visitor{background:#1d56d8;color:white;margin:0 0 12px 18px}.msg small{display:block;font-size:11px;margin-bottom:3px}#reply{display:flex;gap:8px;padding:10px;border-top:1px solid #e0e8f2}#reply textarea{min-height:46px;height:46px;resize:none}#reply button{padding:8px 12px}footer{padding:10px 15px;background:#f6f9fd;border-top:1px solid #e0e8f2}#whatsapp{display:block;background:#128c4a;color:white;padding:10px;text-align:center;border-radius:9px;text-decoration:none;font-weight:650}footer p{font-size:11px;margin:6px 0}.secondary{background:transparent;color:#1d56d8;font-size:12px;padding:4px 0;margin-right:15px}#status{margin:0;padding:0 15px 8px;color:#8e3434;font-size:12px}#reset{padding:15px;border-top:1px solid #e0e8f2}#reset p{margin:0 0 8px}#reset button{margin-right:8px}@media(max-width:420px){:host{left:12px;bottom:12px}#panel{max-width:calc(100vw - 24px);max-height:calc(100dvh - 90px);bottom:55px}#launcher{padding:10px 14px}}
 </style><button id="launcher" aria-expanded="false" aria-controls="panel">Chat with Neloy</button><section id="panel" role="dialog" aria-label="Chat with Neloy Digital Solutions" hidden><header><div><strong>Neloy Digital Solutions</strong><small>Tell us what you want to build</small></div><button id="close" aria-label="Minimize chat">×</button></header><form id="start"><h2>Let’s talk about your project</h2><p>Share a few details to start your conversation.</p><label for="name">Your name</label><input id="name" autocomplete="name" required minlength="2" maxlength="80"><label for="enquiry">How can we help?</label><textarea id="enquiry" required minlength="5" maxlength="600" placeholder="A website, design, video, or something else…"></textarea><p class="small">Your details and messages are saved for our team to reply. Please avoid sensitive information. <a href="/privacy">Privacy policy</a></p><button>Start conversation</button></form><div id="conversation" hidden><div id="messages" role="log" aria-live="polite" aria-label="Chat messages"></div><form id="reply"><textarea id="draft" aria-label="Your message" placeholder="Write a message…" required maxlength="1000"></textarea><button>Send</button></form></div><p id="status" role="status"></p><footer><a id="whatsapp" target="_blank" rel="noopener noreferrer">Continue on WhatsApp ↗</a><p>WhatsApp opens with your enquiry. Tap Send there to deliver it.</p><button id="copy" class="secondary">Copy summary</button><button id="new" class="secondary" hidden>Start a new chat</button></footer><div id="reset" hidden><p>Start a new chat? Your current chat stays in our inbox.</p><button id="confirm">Start new</button><button id="cancel">Keep chatting</button></div></section>`;
 const $=s=>root.querySelector(s);let session=null,chat=null,busy=false,pending=null,last='',polling=false;
 try{session=JSON.parse(sessionStorage.getItem('nds_live_chat')||'null');}catch{}
 const uid=()=>{const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};
 const summary=()=>`Hello Neloy Digital Solutions,\nName: ${chat?.name||$('#name').value.trim()}\nEnquiry: ${chat?.enquiry||$('#enquiry').value.trim()}${chat?'\nChat reference: '+chat.id.slice(0,8):''}${chat?.messages.filter(m=>m.role==='visitor').length?'\nMessages:\n'+chat.messages.filter(m=>m.role==='visitor').map(m=>m.body).join('\n'):''}`;
 function whatsapp(){let s=summary();while(('https://wa.me/60183946761?text='+encodeURIComponent(s)).length>3000)s=s.slice(0,s.length-50);$('#whatsapp').href='https://wa.me/60183946761?text='+encodeURIComponent(s);}
 async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(session?{Authorization:'Bearer '+session.token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j.error||'Unable to connect. Please try again or use WhatsApp.'),{status:r.status});return j;}
 function draw(data){chat=data;$('#start').hidden=true;$('#conversation').hidden=false;$('#new').hidden=false;const next=JSON.stringify(data.messages);if(next!==last){const list=$('#messages'),atBottom=list.scrollHeight-list.scrollTop-list.clientHeight<70;list.replaceChildren();const en=document.createElement('div');en.className='msg visitor';en.textContent=data.enquiry;list.append(en);for(const m of data.messages){const el=document.createElement('div');el.className='msg '+m.role;const label=document.createElement('small');label.textContent=m.role==='assistant'?'Automatic welcome':m.role==='owner'?'Neloy team':'You';el.append(label,document.createTextNode(m.body));list.append(el);}if(atBottom||!last)list.scrollTop=list.scrollHeight;last=next;}whatsapp();}
 async function refresh(){if(!session||busy||polling||$('#panel').hidden||document.hidden)return;polling=true;try{draw(await api('/api/chat/'+session.id));$('#status').textContent='';}catch(e){$('#status').textContent=e.message;if(e.status===401||e.status===404){session=null;sessionStorage.removeItem('nds_live_chat');$('#start').hidden=false;$('#conversation').hidden=true;$('#new').hidden=true;chat=null;last='';}}finally{polling=false;}}
 $('#launcher').onclick=()=>{const open=$('#panel').hidden;$('#panel').hidden=!open;$('#launcher').setAttribute('aria-expanded',String(open));if(open){refresh();(session?$('#draft'):$('#name')).focus();}};
 function close(){$('#panel').hidden=true;$('#launcher').setAttribute('aria-expanded','false');$('#launcher').focus();}
 $('#close').onclick=close;root.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
 $('#start').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=$('#start button');b.disabled=true;$('#status').textContent='Starting…';try{const j=await api('/api/chat',{name:$('#name').value,enquiry:$('#enquiry').value});session={id:j.id,token:j.token};try{sessionStorage.setItem('nds_live_chat',JSON.stringify(session));}catch{}draw(j);$('#status').textContent='';$('#draft').focus();}catch(e){$('#status').textContent=e.message;}finally{busy=false;b.disabled=false;}};
 $('#reply').onsubmit=async e=>{e.preventDefault();const value=$('#draft').value.trim();if(!value||busy)return;busy=true;$('#reply button').disabled=true;if(!pending||pending.body!==value)pending={id:uid(),body:value};try{draw(await api('/api/chat/'+session.id,pending));$('#draft').value='';pending=null;$('#status').textContent='Message saved. The team will reply when available.';}catch(e){$('#status').textContent=e.message;}finally{busy=false;$('#reply button').disabled=false;}};
 $('#draft').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#reply').requestSubmit();}};
 $('#name').oninput=whatsapp;$('#enquiry').oninput=whatsapp;$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(summary());$('#status').textContent='Summary copied.';}catch{$('#status').textContent='Copy is unavailable. Use Continue on WhatsApp.';}};
 $('#new').onclick=()=>{$('#reset').hidden=false;$('#confirm').focus();};$('#cancel').onclick=()=>{$('#reset').hidden=true;};$('#confirm').onclick=()=>{session=null;chat=null;last='';pending=null;sessionStorage.removeItem('nds_live_chat');$('#start').reset();$('#draft').value='';$('#messages').replaceChildren();$('#conversation').hidden=true;$('#start').hidden=false;$('#new').hidden=true;$('#reset').hidden=true;$('#status').textContent='';whatsapp();$('#name').focus();};
 if(session){$('#start').hidden=true;$('#conversation').hidden=false;$('#new').hidden=false;}
 whatsapp();setInterval(refresh,4000);document.addEventListener('visibilitychange',refresh);
}
