export function inboxClient(){
const $=s=>document.querySelector(s);let selected=null,rows=[],busy=false,pending=null,polling=false;
$('#token').value=sessionStorage.getItem('nds_admin_token')||sessionStorage.getItem('nds_token')||'';
function message(s){$('#status').textContent=s;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json',Authorization:'Bearer '+$('#token').value.trim()},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to connect.');return j;}
function render(){const list=$('#list');list.replaceChildren();if(!rows.length)list.textContent='No chats yet.';for(const c of rows){const b=document.createElement('button');b.className='card';b.textContent=c.name+' — '+c.enquiry;b.setAttribute('aria-pressed',String(c.id===selected));b.onclick=()=>{selected=c.id;$('#draft').value='';pending=null;loadChat();render();};list.append(b);}}
async function loadChat(){if(!selected)return;const c=await api('/api/chat-inbox/'+selected);$('#name').textContent=c.name;$('#enquiry').textContent=c.enquiry;const list=$('#messages');const atBottom=list.scrollHeight-list.scrollTop-list.clientHeight<60;const value=JSON.stringify(c.messages);if(value!==list.dataset.value){list.replaceChildren();for(const m of c.messages){const el=document.createElement('p');el.className='msg';el.textContent=(m.role==='visitor'?'Visitor':m.role==='owner'?'Neloy team':'Automatic welcome')+': '+m.body;list.append(el);}list.dataset.value=value;if(atBottom)list.scrollTop=list.scrollHeight;}$('#reply').hidden=false;}
async function load(){if(busy||polling)return;polling=true;try{const t=$('#token').value.trim();if(!t)throw new Error('Enter your existing ADMIN_TOKEN.');sessionStorage.setItem('nds_admin_token',t);const j=await api('/api/chat-inbox');rows=j.conversations;render();await loadChat();message(rows.length+' conversation(s). Updates every 5 seconds while this tab is open.');}catch(e){message(e.message);}finally{polling=false;}}
$('#load').onclick=load;$('#reply').onsubmit=async e=>{e.preventDefault();const body=$('#draft').value.trim();if(!selected||!body||busy)return;busy=true;$('#send').disabled=true;if(!pending||pending.body!==body)pending={id:crypto.randomUUID(),body};try{await api('/api/chat-inbox/'+selected,pending);$('#draft').value='';pending=null;await loadChat();message('Reply saved. The visitor receives it in their website chat.');}catch(e){message(e.message);}finally{busy=false;$('#send').disabled=false;}};
setInterval(()=>{if(!document.hidden&&$('#token').value.trim())load();},5000);
}
export const INBOX_HTML=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Chat Inbox | Neloy Digital Solutions</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6fb;color:#153052;font:15px/1.5 system-ui}main{width:min(1150px,calc(100% - 28px));margin:25px auto}a{color:#1d56d8}.bar{display:flex;gap:10px;margin:20px 0}input,textarea,button{font:inherit;border:1px solid #bdcddd;border-radius:9px;padding:10px}button{cursor:pointer;background:#1d56d8;color:#fff}input{min-width:0}.grid{display:grid;grid-template-columns:320px 1fr;gap:20px}.panel{background:#fff;border:1px solid #d5e0ee;border-radius:14px;padding:18px;min-width:0}.card{display:block;width:100%;text-align:left;background:#f1f6fd;color:#153052;margin-bottom:8px;overflow-wrap:anywhere}.card[aria-pressed=true]{border:2px solid #1d56d8}#messages{max-height:50vh;overflow:auto}.msg,#enquiry{white-space:pre-wrap;overflow-wrap:anywhere}.msg{padding:12px;background:#edf3fa;border-radius:10px}#reply{display:flex;gap:10px}textarea{min-width:0;width:100%;height:80px}#status{color:#5b6f87}[hidden]{display:none!important}@media(max-width:650px){.grid{grid-template-columns:1fr}.bar{flex-wrap:wrap}.bar input{width:100%}}</style></head><body><main><a href="/admin">← Lead dashboard</a> · <a href="/">Website</a><h1>Website chat inbox</h1><p>Use your existing admin token. Website replies appear here; WhatsApp conversations continue in your normal WhatsApp after the visitor sends their message.</p><div class="bar"><input id="token" type="password" aria-label="ADMIN_TOKEN" placeholder="ADMIN_TOKEN" autocomplete="off"><button id="load">Load chats</button></div><p id="status" role="status"></p><div class="grid"><section class="panel" id="list" aria-label="Conversations">Load chats to see enquiries.</section><section class="panel"><h2 id="name">Select a conversation</h2><p id="enquiry"></p><div id="messages" role="log" aria-live="polite"></div><form id="reply" hidden><textarea id="draft" aria-label="Reply to visitor" required maxlength="1000" placeholder="Reply to this visitor…"></textarea><button id="send">Send reply</button></form></section></div></main><script src="/chat-assets/inbox.js" defer></script></body></html>`;
