// Editorial source only. Bodies are trusted, reviewed HTML, never request input.
export const BLOG_ORIGIN = 'https://neloydigitalsolutions.com';
export const PUBLISHER = 'Neloy Digital Solutions';
export const articles = [
  {
    title: 'What makes a business website look trustworthy? 10 practical checks',
    slug: 'what-makes-a-business-website-look-trustworthy',
    metaTitle: 'What Makes a Business Website Look Trustworthy? | Neloy Digital Solutions',
    metaDescription: 'Use 10 practical checks to improve trust on a small-business website, including clear services, contact details, mobile usability, proof, security and branding.',
    category: 'Website Design',
    published: true,
    datePublished: '2026-10-08T21:20:00+06:00',
    dateModified: '2026-10-08T21:20:00+06:00',
    summary: 'A practical trust checklist for small-business websites: clear identity, useful information, real proof, mobile usability and transparent contact details.',
    image: {src:'/assets/blog/website-trust-checklist.svg', alt:'Checklist showing 10 practical trust signals for a small-business website', width:1200, height:630, caption:'10 practical checks for a trustworthy business website.'},
    serviceLinks: [{path:'/website-design', label:'Website design services'}, {path:'/logo-design', label:'Logo design services'}, {path:'/digital-marketing', label:'SEO and AEO digital marketing'}],
    relatedSlugs: ['website-redesign-or-new-website', 'prepare-a-logo-design-brief', 'prepare-footage-for-video-editing'],
    sections: [
      {id:"trust-start", title:"What makes a website feel trustworthy?", body:"<p>A trustworthy business website makes it easy for visitors to understand who you are, what you offer, how to contact you and why they should believe your claims. Trust does not come from one badge or one design trend. It comes from several small signals working together: clear information, consistent branding, real proof, usable pages and transparent ways to get in touch.</p><p>Use the ten checks below as a practical review. You do not need to rebuild a website just because one item needs improvement. Start with the issues that make a visitor hesitate or prevent them from completing an important task.</p>"},
      {id:"identity", title:"1. Make the business identity obvious", body:"<p>Visitors should not have to guess which company they are dealing with. Keep the business name, logo and basic positioning easy to find. The wording on the homepage should quickly explain the type of customer you help and the main service or result you provide.</p><p>Consistency matters here. If the website uses one business name while social profiles, proposals or invoices use another variation, people may wonder whether they have reached the correct company. Keep the approved name, logo and key brand elements consistent across the main customer touchpoints.</p>"},
      {id:"services", title:"2. Explain services clearly", body:"<p>Service pages should explain the work in normal language. A page that only says “innovative solutions” or “premium service” gives visitors little evidence about what they can actually request. Describe the deliverable, the typical use case and the main steps in the process.</p><p>For example, a web design page can explain whether the work covers business websites, landing pages, responsive layouts, enquiry forms or e-commerce. A video editing page can explain the types of edits, file handover and review process. Specific information helps a potential client decide whether the service matches the project.</p>"},
      {id:"contact", title:"3. Make contact information easy to verify", body:"<p>Make it obvious how a real person can reach the business. A contact form can be useful, but it should not be the only sign that a company exists. Depending on the business, useful contact information can include a professional email address, phone or messaging option, social profiles and a clear contact page.</p><p>Do not publish contact methods that are never monitored. A smaller set of accurate contact options is better than several outdated links. Test forms regularly and confirm that the acknowledgement message tells the visitor what happens next.</p>"},
      {id:"mobile", title:"4. Check the mobile experience and readability", body:"<p>Many visitors will judge the website from a phone. Check whether the main message is readable without zooming, navigation is easy to use, buttons are large enough to tap and forms do not require awkward horizontal scrolling.</p><p>Also look for visual friction: very small text, weak contrast, crowded sections, pop-ups that cover the page or animations that distract from the main task. A professional website does not need to be visually complicated. It needs to make important information easy to find and use.</p>"},
      {id:"proof", title:"5. Show real proof of work", body:"<p>Show evidence that supports the claims on the page. Useful proof can include completed projects, before-and-after examples, screenshots, case-study details, client feedback and links to relevant live work when permission allows it.</p><p>Keep proof specific. “We provide excellent service” is a claim. A portfolio example that explains the type of project, the work completed and the result is evidence a visitor can evaluate. Testimonials are stronger when they are clearly connected to a real project or client context.</p>"},
      {id:"security", title:"6. Use security and privacy signals responsibly", body:"<p>HTTPS helps protect information sent between the visitor and the website, but the padlock alone does not prove that a business is trustworthy. Pair technical security with transparency: a clear privacy policy, sensible form fields, accurate terms where relevant and honest explanations of how enquiries are handled.</p><p>Avoid requesting sensitive information when it is not necessary for the first conversation. Keep software and integrations maintained, remove broken scripts and make sure important pages load without browser security warnings.</p>"},
      {id:"consistency", title:"7. Keep branding consistent across platforms", body:"<p>Your website, social profiles, proposals and marketing graphics do not need to look identical, but they should feel like the same business. Reuse the approved logo, core colours, tone of voice and service terminology. Consistency makes it easier for someone who discovered you on another platform to recognise that they arrived at the correct website.</p><p>This is also why small details matter. Different spellings of the company name, outdated profile images or conflicting service descriptions can create unnecessary doubt.</p>"},
      {id:"next-step", title:"8. Give visitors a clear next step", body:"<p>Every important page should make the next step clear. That might be requesting a quote, viewing relevant projects, sending a brief, booking a conversation or reading a related guide. The action should match the page rather than forcing every visitor into the same generic button.</p><p>Use specific call-to-action wording where possible. “Discuss your website project” gives more context than “Click here.” Make sure the destination works and does not surprise the visitor with an unrelated page.</p>"},
      {id:"freshness", title:"9. Keep important information accurate", body:"<p>Old information can weaken confidence even when the design still looks polished. Review service descriptions, team details, copyright years, portfolio links, contact information and important policy pages periodically. Remove offers that are no longer available and repair links that lead to missing pages.</p><p>You do not need to change content just to make a page look recently updated. Change the date when the information itself changes. Accuracy is more useful than artificial freshness.</p>"},
      {id:"checklist", title:"10. Run a simple trust checklist", body:"<div class=\"blog-table\"><table><caption>Quick website trust review</caption><thead><tr><th scope=\"col\">Check</th><th scope=\"col\">Question to ask</th></tr></thead><tbody><tr><td>Identity</td><td>Can a new visitor immediately tell who the business is?</td></tr><tr><td>Services</td><td>Can they understand what they can actually request?</td></tr><tr><td>Contact</td><td>Is there a clear, working way to reach the business?</td></tr><tr><td>Mobile</td><td>Can the main task be completed comfortably on a phone?</td></tr><tr><td>Proof</td><td>Are claims supported by real work or relevant client evidence?</td></tr><tr><td>Security</td><td>Does the site use HTTPS and explain privacy appropriately?</td></tr><tr><td>Brand</td><td>Does the website match the business seen on other platforms?</td></tr><tr><td>Next step</td><td>Does each important page give the visitor a sensible action?</td></tr><tr><td>Accuracy</td><td>Are services, links and contact details still current?</td></tr></tbody></table></div><p>Fix the clearest trust blockers first. If the site already has strong URLs, useful content and working forms, improve those areas without rebuilding everything. If you are planning a broader update, our <a href=\"https://neloydigitalsolutions.com/website-design\">website design service</a> explains how we structure projects around requirements, scope and budget.</p>"}
    ]
  },
  {
    title: 'Website redesign or a new website? A practical decision checklist',
    slug: 'website-redesign-or-new-website',
    metaTitle: 'Website Redesign or New Website? | Neloy Digital Solutions',
    metaDescription: 'Decide whether to improve your existing website or rebuild it using a practical checklist for mobile usability, content, maintenance and enquiry forms.',
    category: 'Website Design',
    published: true,
    datePublished: '2026-10-08T18:45:00+06:00',
    dateModified: '2026-10-08T18:45:00+06:00',
    summary: 'Start with the problems customers face, then decide which parts of your website are worth keeping.',
    serviceLinks: [{path:'/website-design', label:'Website design services'}],
    relatedSlugs: ['prepare-a-logo-design-brief', 'prepare-footage-for-video-editing'],
    sections: [
      {id:'start-with-the-task', title:'Start with one customer task', body:`<p>A website that looks dated does not automatically need a rebuild. If visitors can understand your offer, read the page on a phone and send an enquiry, a focused redesign may solve the remaining problems. A rebuild becomes more useful when the platform prevents essential changes or when maintaining the existing site costs more effort than replacing it.</p><p>Choose one task to test first: requesting a quote, checking a service or viewing a relevant project. Ask someone unfamiliar with the business to complete it on a phone. Avoid explaining where to click. Write down the point where they hesitate, the information they cannot find and any step that fails. This gives you a concrete problem list instead of a vague instruction to make the site more modern.</p>`},
      {id:'keep-or-replace', title:'Separate presentation problems from platform problems', body:`<div class="blog-table"><table><caption>Common findings and the first change to consider</caption><thead><tr><th scope="col">Finding</th><th scope="col">First option to investigate</th></tr></thead><tbody><tr><td>Text is cramped or buttons are hard to use on phones</td><td>Improve responsive layout and spacing</td></tr><tr><td>Visitors cannot tell what the business offers</td><td>Rewrite and reorganise service content</td></tr><tr><td>Useful projects exist but are difficult to find</td><td>Improve portfolio organisation and links</td></tr><tr><td>The platform cannot support an essential workflow</td><td>Compare a supported integration with a rebuild</td></tr><tr><td>Routine changes repeatedly break unrelated pages</td><td>Investigate the underlying implementation before choosing a solution</td></tr></tbody></table></div><p>These are starting points, not automatic verdicts. A broken enquiry form, for example, may be a small configuration issue. Rebuilding every page before diagnosing it can spend the budget without addressing the actual cause.</p>`},
      {id:'inventory', title:'Make a short inventory before requesting a quote', body:`<p>Create a list with four columns: page URL, purpose, what works and what needs attention. Include service pages, enquiry pages and portfolio pages. Note which pages already bring relevant visitors or enquiries if you have reliable analytics. Keep a separate list of integrations such as email notifications, appointment booking and customer management.</p><p>Mark each item as keep, improve, replace or investigate. For example, a strong service page might need only clearer spacing and a shorter form. An unused feature might not belong in the next version at all. Give the designer the inventory and the customer task from the first step. Both help define scope more accurately than sending a collection of attractive reference sites.</p>`},
      {id:'protect-existing-pages', title:'Protect pages that already work', body:`<p>During a redesign, preserve existing page addresses whenever practical. Record page titles, descriptions, canonical URLs, important headings and internal links before work starts. If an address genuinely must change, plan where its visitors should go rather than leaving the old link broken.</p><p>Do not treat a redesign as a reason to rewrite every useful paragraph. Keep accurate service information and real examples. Test enquiry forms, confirmation messages, mobile navigation and contact links in a separate preview. A design can look complete while the customer journey still fails at the final step.</p>`},
      {id:'example', title:'Example: a small consultancy website', body:`<p>Imagine a consultancy with six pages, a working enquiry form and useful case studies. Customers complain that the phone layout is crowded and that the main service is unclear. A focused redesign could improve the service introduction, simplify the mobile menu and make case studies easier to scan while retaining the existing URLs.</p><p>If that same consultancy needs a client portal that its current platform cannot support safely or maintainably, compare the cost of an integration with a rebuild. Write down the required portal tasks before selecting a platform. The decision should follow the workflow, not a preference for a particular tool.</p>`},
      {id:'brief', title:'Use this brief to agree the next step', body:`<ul><li>Our main customer task is: ___.</li><li>The three problems we observed are: ___.</li><li>Pages and integrations we must keep are: ___.</li><li>Required new functionality is: ___.</li><li>Our budget range, deadline and approval contact are: ___.</li><li>We will accept the work when these tasks pass on desktop and mobile: ___.</li></ul><p>Ask for a recommendation with reasons, a clear list of included work and a separate list of assumptions. If the evidence supports incremental improvements, start there. If it supports a rebuild, use the inventory as the migration checklist. You can review our <a href="https://neloydigitalsolutions.com/website-design">website design service</a> when you need help defining that scope.</p>`}
    ]
  },
  {
    title: 'How to prepare a logo design brief that reduces revision loops',
    slug: 'prepare-a-logo-design-brief',
    metaTitle: 'How to Prepare a Logo Design Brief | Neloy Digital Solutions',
    metaDescription: 'Prepare a clear logo brief with audience, use cases, references, file requirements and a simple approval process before your design project starts.',
    category: 'Branding', published: true,
    datePublished: '2026-10-08T18:45:00+06:00', dateModified: '2026-10-08T18:45:00+06:00',
    summary: 'Give your designer decisions they can use: who the logo is for, where it will appear and how you will approve it.',
    serviceLinks: [{path:'/logo-design', label:'Logo design services'}, {path:'/social-media-design', label:'Social media design services'}],
    relatedSlugs: ['website-redesign-or-new-website', 'prepare-footage-for-video-editing'],
    sections: [
      {id:'business', title:'Describe the business before describing a shape', body:`<p>A useful logo brief explains what the business does, who it serves and where the identity will be used. It does not need to dictate every design detail. The goal is to give the designer enough context to make choices and give you a consistent basis for reviewing them.</p><p>Start with the exact business name, any approved tagline and a plain description of the offer. Include the spelling and capitalisation that must appear. If the business name is changing, resolve that first. Designing around an unsettled name can create avoidable work across the logo, website and social profiles.</p><p>Then describe the audience in practical terms. A local repair company may need to look dependable and be readable on a moving vehicle. A specialist consultant may need to feel credible in presentations and proposals. These use cases provide more direction than asking for a logo that looks premium.</p>`},
      {id:'use-cases', title:'List the places the logo must work', body:`<p>Put the most demanding use cases near the top of the brief. Think about a small social profile image, a narrow website header, an invoice, a printed sign or clothing. A detailed mark that looks attractive in a large preview may lose its identity at a small size.</p><ul><li>Website header: note whether space is wide or compact.</li><li>Social profiles: ask to see the mark inside a circular crop.</li><li>Print: identify the intended item and ask the printer about its requirements.</li><li>Single-colour use: include situations where colour printing is unavailable.</li><li>Dark backgrounds: request an appropriate contrasting version if needed.</li></ul><p>Do not ask for every possible variation without a use case. Agree the necessary versions and deliverables as part of the project scope. This keeps the work focused and makes the final handover easier to check.</p>`},
      {id:'references', title:'Explain what you like about references', body:`<p>Collect a few references and add a sentence beside each one. You might like the open spacing, simple lettering or restrained colour. You might dislike an overly decorative symbol or a typeface that is hard to read. Those comments help the designer separate your preference from the specific artwork.</p><p>References are discussion material, not instructions to copy another business. Describe the quality you want rather than requesting the same mark with your name underneath. Also share the colours or existing brand elements that must remain, and explain whether they are fixed requirements or preferences.</p>`},
      {id:'feedback', title:'Choose an approver and use specific feedback', body:`<p>Decide who gives final approval before the first concepts arrive. If several people need input, collect their comments into one response. Conflicting instructions sent separately can cause a designer to undo one person's changes while responding to another.</p><p>Review a concept against the brief: readability, audience fit, small-size use and required applications. Replace feedback such as “make it pop” with an observation and a goal. For example: “The business name becomes hard to read at our website header size; please improve its legibility.” The designer can act on that without guessing which feature to change.</p><p>Distinguish corrections from a new direction. Correcting a misspelled name is different from changing the audience or switching from a wordmark to a detailed emblem after a direction has been approved. Agree how those scope changes will be handled.</p>`},
      {id:'handover', title:'Agree the handover before the work begins', body:`<p>Ask which editable or vector files and which exported images are included. An SVG or suitable print vector can serve different needs from a transparent PNG. A JPEG is useful in some contexts but does not support a transparent background. Match the file set to the actual uses rather than judging the handover by the number of files.</p><p>Clarify ownership, font licensing, colour specifications and any restrictions in the agreement. Keep the approved artwork in one clearly named folder so old concepts are not accidentally used later. When the identity is applied to posts, use the same approved logo version and colour references across the <a href="https://neloydigitalsolutions.com/social-media-design">social media designs</a>.</p>`},
      {id:'copyable-brief', title:'A compact brief you can fill in', body:`<ul><li>Exact business name and tagline: ___.</li><li>What we do and who we serve: ___.</li><li>The three qualities we want to communicate: ___.</li><li>Main places the logo will appear: ___.</li><li>Elements we must keep or avoid: ___.</li><li>References, with reasons: ___.</li><li>Required file formats and versions: ___.</li><li>Budget, deadline and final approver: ___.</li></ul><p>Before sending the brief, check that the requirements do not contradict each other. “Very detailed” and “recognisable at a tiny size” may need a discussion about separate versions. A short, settled brief gives the project a clearer start. Our <a href="https://neloydigitalsolutions.com/logo-design">logo design service page</a> explains the project process if you are preparing to commission work.</p>`}
    ]
  },
  {
    title: 'What to send your video editor before the first edit',
    slug: 'prepare-footage-for-video-editing',
    metaTitle: 'What to Send Your Video Editor | Neloy Digital Solutions',
    metaDescription: 'Organise footage, audio, brand assets and editing instructions with a practical handover checklist for reels, podcasts and business videos.',
    category: 'Video Editing', published: true,
    datePublished: '2026-10-08T18:45:00+06:00', dateModified: '2026-10-08T18:45:00+06:00',
    summary: 'A clean handover helps your editor spend time on the story instead of searching for files and guessing your requirements.',
    serviceLinks: [{path:'/video-editing', label:'Video editing services'}],
    relatedSlugs: ['website-redesign-or-new-website', 'prepare-a-logo-design-brief'],
    sections: [
      {id:'outcome', title:'Start with the outcome and delivery format', body:`<p>Before uploading footage, write one sentence describing what the finished video should do. An educational reel, a podcast highlight and a business introduction need different choices about pacing, context and captions. Give the editor a viewer and a purpose, not just a target duration.</p><p>State the intended platform, aspect ratio, approximate length and language. If you need several versions, list them separately. For example, you might need a vertical highlight and a horizontal full conversation. Ask the editor to confirm whether both are included. A change in framing can require more than exporting the same timeline at a different size.</p><p>Also state the deadline and who will approve the demo. Leave time for review between the first version and final delivery. A delivery date without an agreed review window can turn ordinary feedback into a last-minute rush.</p>`},
      {id:'files', title:'Organise files by what they contain', body:`<p>Use a simple folder structure such as Footage, Audio, Brand Assets, References and Brief. Keep original recordings unchanged. Name files so someone else can identify the camera, session or take without opening each one. For example, “interview-camera-a-take-02” is more useful than “final-final-new”.</p><p>If there are multiple cameras and a separate microphone, identify which files belong to the same session. Include a note about claps, sync markers or recording interruptions if you know them. Do not hide recording problems: a missing audio segment or a restart is easier to plan around when the editor knows about it.</p><p>Check the upload by opening the shared folder from the recipient's perspective. Confirm that the files are complete and that the editor has the agreed access. Send a single clear link rather than spreading assets across several messages.</p>`},
      {id:'selects', title:'Use timecodes to identify priorities', body:`<p>You do not have to select every usable moment yourself, but a short list of must-include points is valuable. Give a filename, a time range and the reason it matters. For example: “Interview A, 04:10–04:38: clear explanation of the customer problem.” Mark anything that must be removed, such as a private detail or an outdated offer.</p><p>For a short clip, identify the main point and the context needed to understand it. A strong sentence can become misleading if the setup is removed. Ask the editor to preserve the intended meaning while tightening repetition and pauses. If you want the editor to select the highlights, say so and agree how many clips they should propose.</p>`},
      {id:'brand-and-rights', title:'Supply approved brand assets and usable media', body:`<p>Include the approved logo, colour references and any required text. Specify the spelling of names, job titles, technical terms and the final call to action. If captions are needed, provide corrections for words that automatic transcription is likely to misunderstand.</p><p>Tell the editor where supplied music, photos or stock footage came from and whether you have permission for the intended use. Do not assume that a track available in a personal editing app can be reused in every commercial context. If permission is unclear, flag it before editing rather than waiting until export.</p><p>A reference video can communicate pacing or caption style. Explain which feature you want to learn from; request an original treatment instead of copying the whole design. Include anything you want to avoid, such as rapid flashes, oversized captions or distracting sound effects.</p>`},
      {id:'demo', title:'Approve a short demo before the full edit', body:`<p>A short representative sample can settle caption styling, voice clarity, framing and pacing early. Choose a section that includes the main types of footage rather than an unusually simple opening. Review it on a phone with sound and without sound if both matter to your audience.</p><p>Send one consolidated feedback list. Include the timecode, observation and requested outcome: “00:08: the caption covers the product; move it into the clear lower area.” Separate factual corrections from preferences and new requirements. Confirm the agreed direction before the editor applies it across the full video.</p>`},
      {id:'handover-checklist', title:'Final handover checklist', body:`<ul><li>Viewer, purpose, platform, aspect ratio and target length are stated.</li><li>Original footage and matching audio are uploaded and accessible.</li><li>Must-include and must-remove moments have filenames and timecodes.</li><li>Logo, required wording and caption spelling are approved.</li><li>Rights or restrictions for supplied music and media are explained.</li><li>Demo reviewer, revision process and delivery date are agreed.</li><li>Final export, subtitle and project-file requirements are confirmed.</li></ul><p>After delivery, watch the complete export rather than checking only the opening. Confirm captions, audio, the final message and the file versions. Keep approved exports separate from drafts. For help with reels, podcasts or promotional edits, see our <a href="https://neloydigitalsolutions.com/video-editing">video editing services</a> and share this checklist with your project brief.</p>`}
    ]
  }
];

// Canonicals and publisher are derived to keep every article on the main domain.
export function publishedArticles(now = Date.now()) {
  return articles.filter(a => a.published && Date.parse(a.datePublished) <= now)
    .map(a => ({...a, canonicalURL: `${BLOG_ORIGIN}/blog/${a.slug}`, publisher: PUBLISHER}))
    .sort((a,b) => b.datePublished.localeCompare(a.datePublished) || a.slug.localeCompare(b.slug));
}
