import { BLOG_ORIGIN, PUBLISHER, publishedArticles } from './articles.js';
import { PREMIUM_THEME } from '../design/premium-theme.js';
import { addFavicon } from '../assets/favicon.js';

const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href = path => BLOG_ORIGIN + path;
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const displayDate = date => new Intl.DateTimeFormat('en-GB', {day:'numeric', month:'long', year:'numeric', timeZone:'Asia/Dhaka'}).format(new Date(date));
const org = {'@type':'Organization', '@id':href('/#organization'), name:PUBLISHER, url:href('/')};

const STYLE = `<style id="nds-blog-style">
*{box-sizing:border-box}body{margin:0}a{color:#1954b4;text-underline-offset:.2em}a:hover{text-decoration-thickness:2px}a:focus-visible{outline:3px solid #1954b4;outline-offset:5px}img{max-width:100%;height:auto}.blog-wrap{width:min(1120px,calc(100% - 40px));margin-inline:auto}.blog-header{border-bottom:1px solid #d8e8f5;background:white}.blog-nav{display:flex;justify-content:space-between;align-items:center;gap:24px;padding-block:22px}.blog-brand{font-size:1.05rem;font-weight:800;text-decoration:none;color:#102844}.blog-nav nav{display:flex;gap:20px;flex-wrap:wrap;font-size:.95rem}.blog-skip{position:absolute;left:20px;top:-80px;background:#fff;padding:12px;z-index:10}.blog-skip:focus{top:8px}.blog-crumbs{display:flex;flex-wrap:wrap;gap:10px;list-style:none;padding:0;margin:26px 0;font-size:.9rem}.blog-crumbs li+li:before{content:'/';color:#536981;margin-right:10px}.blog-hero{max-width:850px;margin-block:40px 46px}.blog-kicker{color:#1954b4;font-weight:700;font-size:.95rem;margin:0 0 12px}.blog-hero h1{font-size:clamp(2rem,4.5vw,3.5rem);line-height:1.13;margin:0 0 20px}.blog-deck{font-size:1.15rem;color:#536981;max-width:65ch}.blog-meta{font-size:.9rem;color:#536981}.blog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;margin-bottom:70px}.blog-card{border:1px solid #d8e8f5;border-top:3px solid #1954b4;border-radius:14px;padding:26px;background:#fff}.blog-card h2,.blog-card h3{font-size:1.35rem;line-height:1.3;margin:12px 0}.blog-card h2 a,.blog-card h3 a{text-decoration:none;color:#102844}.blog-card p{color:#536981;margin-bottom:0}.blog-layout{display:grid;grid-template-columns:minmax(0,740px) minmax(180px,1fr);gap:56px;align-items:start}.blog-body{font-size:1.0625rem;overflow-wrap:anywhere}.blog-body section{margin-bottom:38px;scroll-margin-top:24px}.blog-body h2{font-size:1.65rem;line-height:1.25;margin:0 0 16px}.blog-body p{margin:0 0 18px}.blog-body li{margin-bottom:10px}.blog-body ul{padding-left:24px}.blog-toc{padding:22px;background:#f3f8fd;border:1px solid #d8e8f5;border-radius:14px;font-size:.95rem}.blog-toc h2{font-size:1.05rem;margin-top:0}.blog-toc ol{padding-left:20px;margin-bottom:0}.blog-toc li{margin-bottom:12px}.blog-table{overflow:auto;margin:24px 0;border:1px solid #d8e8f5;border-radius:10px}table{border-collapse:collapse;width:100%;font-size:1rem}caption{text-align:left;padding:16px;font-weight:700}th,td{text-align:left;vertical-align:top;padding:16px;border-top:1px solid #d8e8f5}th{background:#f3f8fd}.blog-related{border-top:1px solid #d8e8f5;padding-top:32px;margin-top:32px}.blog-related .blog-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.blog-services{padding:24px 0;border-top:1px solid #d8e8f5}.blog-services ul{padding-left:22px}.blog-footer{background:#102844;color:#fff;padding:32px 0;margin-top:40px}.blog-footer a{color:#fff}.blog-footer nav{display:flex;flex-wrap:wrap;gap:20px}.blog-footer p{font-size:.9rem}.blog-image{margin:24px 0}.blog-image figcaption{font-size:.9rem;color:#536981}
@media(max-width:850px){.blog-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.blog-layout{grid-template-columns:1fr;gap:28px}.blog-toc{grid-row:1}.blog-hero{margin-top:28px}}
@media(max-width:560px){.blog-wrap{width:calc(100% - 32px)}.blog-nav{align-items:flex-start;flex-direction:column;gap:14px}.blog-grid,.blog-related .blog-grid{grid-template-columns:1fr}.blog-hero h1{font-size:2rem}.blog-card{padding:22px}.blog-crumbs{font-size:.875rem}.blog-body{font-size:1rem}th,td{padding:12px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}}
</style>`;

function breadcrumbs(article) {
  const items = [{name:'Home',url:href('/')}, {name:'Blog',url:href('/blog')}];
  if (article) items.push({name:article.title,url:article.canonicalURL});
  return {items, schema:{'@type':'BreadcrumbList',itemListElement:items.map((item,i)=>({'@type':'ListItem',position:i+1,name:item.name,item:item.url}))}};
}
function cards(list, level = 'h2') {
  return list.map(a=>`<article class="blog-card"><p class="blog-kicker">${esc(a.category)}</p><${level}><a href="${esc(a.canonicalURL)}">${esc(a.title)}</a></${level}><div class="blog-meta"><time datetime="${esc(a.datePublished)}">${displayDate(a.datePublished)}</time></div><p>${esc(a.summary)}</p></article>`).join('');
}
function shell({title, description, canonical, crumbs, schema, content, article, noindex = false}) {
  const imageMeta = article?.image ? `<meta property="og:image" content="${esc(href(article.image.src))}">` : '';
  return addFavicon(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}">${canonical ? `<link rel="canonical" href="${esc(canonical)}">` : ''}<meta name="robots" content="${noindex ? 'noindex,follow' : 'index,follow,max-image-preview:large'}"><meta name="google-site-verification" content="fpMHNoyt2VVYZjEZNVI1CJ3_0WydoGZPurog2p5qIyY"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:site_name" content="${PUBLISHER}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}">${canonical?`<meta property="og:url" content="${esc(canonical)}">`:''}${imageMeta}<meta name="twitter:card" content="${article?.image?'summary_large_image':'summary'}">${article?`<meta property="article:published_time" content="${esc(article.datePublished)}"><meta property="article:modified_time" content="${esc(article.dateModified)}">`:''}${schema?`<script type="application/ld+json">${json(schema)}</script>`:''}${PREMIUM_THEME}${STYLE}</head><body><a class="blog-skip" href="#blog-main">Skip to content</a><header class="blog-header"><div class="blog-wrap blog-nav"><a class="blog-brand" href="${href('/')}">${PUBLISHER}</a><nav aria-label="Blog navigation"><a href="${href('/blog')}"${!article?' aria-current="page"':''}>Blog</a><a href="${href('/showcase')}">Showcase</a><a href="${href('/#contact')}">Contact</a></nav></div></header><main id="blog-main" class="blog-wrap"><nav aria-label="Breadcrumb"><ol class="blog-crumbs">${crumbs.items.map((item,i)=>`<li>${i===crumbs.items.length-1?`<span aria-current="page">${esc(item.name)}</span>`:`<a href="${esc(item.url)}">${esc(item.name)}</a>`}</li>`).join('')}</ol>${content}</main><footer class="blog-footer"><div class="blog-wrap"><strong>${PUBLISHER}</strong><p>Practical design and digital guidance for small businesses.</p><nav aria-label="Website information"><a href="${href('/')}">Home</a><a href="${href('/blog')}">Blog</a><a href="${href('/team')}">About the team</a><a href="${href('/privacy')}">Privacy Policy</a><a href="${href('/terms')}">Terms &amp; Agreement</a></nav><p>© 2012–2026 ${PUBLISHER}</p></div></footer></body></html>`);
}

export function renderBlog(path, now = Date.now()) {
  const list = publishedArticles(now);
  if (path === '/blog') {
    const crumbs = breadcrumbs();
    return {status:200, html:shell({title:`Blog | ${PUBLISHER}`, description:'Practical guides to website design, branding and video editing, with checklists to help small businesses prepare and improve their digital projects.',canonical:href('/blog'),crumbs,schema:{'@context':'https://schema.org','@graph':[org,crumbs.schema,{'@type':'Blog','@id':href('/blog#blog'),url:href('/blog'),name:`${PUBLISHER} Blog`,publisher:{'@id':org['@id']},blogPost:list.map(a=>({'@type':'BlogPosting',headline:a.title,url:a.canonicalURL,datePublished:a.datePublished}))}]},content:`<header class="blog-hero"><p class="blog-kicker">Neloy Journal</p><h1>Practical guides for your next digital project</h1><p class="blog-deck">Clear decisions, useful checklists and better handovers for websites, branding and video.</p></header><div class="blog-grid">${cards(list)}</div>`})};
  }
  const article = list.find(a => path === `/blog/${a.slug}`);
  if (!article) return {status:404, html:shell({title:`Article not found | ${PUBLISHER}`,description:'This article could not be found. Browse the published guides on the Neloy Digital Solutions blog.',crumbs:breadcrumbs(),noindex:true,content:`<header class="blog-hero"><h1>Article not found</h1><p>Browse our <a href="${href('/blog')}">published guides</a> to find a practical starting point.</p></header>`})};
  const crumbs = breadcrumbs(article);
  const schema = {'@context':'https://schema.org','@graph':[org,crumbs.schema,{'@type':'BlogPosting','@id':article.canonicalURL+'#article',url:article.canonicalURL,headline:article.title,description:article.metaDescription,datePublished:article.datePublished,dateModified:article.dateModified,author:org,publisher:{'@id':org['@id']},inLanguage:'en',articleSection:article.category,mainEntityOfPage:{'@type':'WebPage','@id':article.canonicalURL},isPartOf:{'@type':'Blog','@id':href('/blog#blog'),url:href('/blog')},...(article.image?{image:[href(article.image.src)]}:{})}]};
  const image = article.image ? `<figure class="blog-image"><img src="${esc(href(article.image.src))}" alt="${esc(article.image.alt)}" width="${article.image.width}" height="${article.image.height}">${article.image.caption?`<figcaption>${esc(article.image.caption)}</figcaption>`:''}</figure>` : '';
  const related = list.filter(a=>article.relatedSlugs.includes(a.slug));
  const content = `<article><header class="blog-hero"><p class="blog-kicker">${esc(article.category)}</p><h1>${esc(article.title)}</h1><p class="blog-deck">${esc(article.summary)}</p><p class="blog-meta">By <a href="${href('/team')}">${PUBLISHER}</a> · Published <time datetime="${esc(article.datePublished)}">${displayDate(article.datePublished)}</time>${article.dateModified!==article.datePublished?` · Updated <time datetime="${esc(article.dateModified)}">${displayDate(article.dateModified)}</time>`:''}</p></header>${image}<div class="blog-layout"><div class="blog-body" data-blog-article-body>${article.sections.map(s=>`<section id="${esc(s.id)}"><h2>${esc(s.title)}</h2>${s.body}</section>`).join('')}<section class="blog-services"><h2>Relevant services</h2><ul>${article.serviceLinks.map(s=>`<li><a href="${esc(href(s.path))}">${esc(s.label)}</a></li>`).join('')}</ul></section></div><nav class="blog-toc" aria-label="In this article"><h2>In this article</h2><ol>${article.sections.map(s=>`<li><a href="#${esc(s.id)}">${esc(s.title)}</a></li>`).join('')}</ol></nav></div></article>${related.length?`<section class="blog-related" aria-labelledby="blog-related-title"><h2 id="blog-related-title">Related articles</h2><div class="blog-grid">${cards(related,'h3')}</div></section>`:''}`;
  return {status:200, html:shell({title:article.metaTitle,description:article.metaDescription,canonical:article.canonicalURL,crumbs,schema,content,article})};
}

export function appendBlogSitemap(xml, now = Date.now()) {
  const list = publishedArticles(now);
  const newest = list.map(a=>a.dateModified).sort().at(-1);
  const entries = [{url:href('/blog'),modified:newest},...list.map(a=>({url:a.canonicalURL,modified:a.dateModified}))];
  const additions = entries.filter(e=>!xml.includes(`<loc>${e.url}</loc>`)).map(e=>`<url><loc>${esc(e.url)}</loc>${e.modified?`<lastmod>${esc(e.modified)}</lastmod>`:''}</url>`).join('');
  return xml.replace('</urlset>',additions+'</urlset>');
}
