import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
const base=new URL('../',import.meta.url).href;
const {default:before}=await import(base+'premium-site-wrapper.js');
const {default:after}=await import(base+'src/worker.js');
const {CHAT_TAG}=await import(base+'src/chat/worker.js');
const paths=['/','/website','/showcase','/portfolio','/logo-design','/website-design','/social-media-design','/video-editing','/digital-marketing','/team','/terms','/privacy','/blog','/robots.txt','/sitemap.xml','/llms.txt','/admin','/api/leads','/.env'];
for(const path of paths){const request=()=>new Request('https://neloydigitalsolutions.com'+path);const b=await before.fetch(request(),{},{}),a=await after.fetch(request(),{},{});assert.equal(a.status,b.status,path);assert.deepEqual([...a.headers].filter(([k])=>!['content-length','etag'].includes(k)),[...b.headers].filter(([k])=>!['content-length','etag'].includes(k)),path+' headers');let x=await a.text(),y=await b.text();x=x.replace(CHAT_TAG,'').replace('<nav id="nds-chat-admin-link" style="padding:12px 20px"><a href="/admin/chat">Open website chat inbox →</a></nav>','');assert.equal(x,y,path+' body');}
console.log('PASS 19 routes: identical existing page content, SEO/schema, forms, WhatsApp, analytics, headers and admin after removing only new chat tag/link');
const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE leads(id INTEGER PRIMARY KEY,name TEXT); INSERT INTO leads VALUES(1,'preserved');");
class Stmt{constructor(query){this.query=query;this.args=[];}bind(...args){this.args=args;return this;}async run(){return sql.prepare(this.query).run(...this.args);}async first(){return sql.prepare(this.query).get(...this.args)||null;}async all(){return {results:sql.prepare(this.query).all(...this.args)};}}
const DB={prepare:q=>new Stmt(q),batch:async stmts=>{sql.exec('BEGIN');try{let result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};const env={DB,ADMIN_TOKEN:'test-owner-token'};
const {chatApi}=await import(base+'src/chat/api.js');
async function call(path,{body,token,origin='https://neloydigitalsolutions.com',method}={}){return chatApi(new Request('https://neloydigitalsolutions.com'+path,{method:method||(body?'POST':'GET'),headers:{...(body?{'content-type':'application/json',origin}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined}),env);}
assert.equal((await call('/api/chat-inbox')).status,401);assert.equal((await call('/api/chat',{body:{name:'X',enquiry:'no'}})).status,400);assert.equal((await call('/api/chat',{body:{name:'Test',enquiry:'Test enquiry'},origin:'https://attacker.example'})).status,403);
let r=await call('/api/chat',{body:{name:'QA Bengali বাংলা',enquiry:'Website & logo <script>alert(1)</script>'}});assert.equal(r.status,201);let c=await r.json();assert.equal(c.messages[0].role,'assistant');assert.ok(c.messages[0].body.includes('automatic welcome'));assert.equal((await call('/api/chat/'+c.id)).status,401);assert.equal((await call('/api/chat/'+c.id,{token:'wrong'})).status,401);
const body={id:crypto.randomUUID(),body:'Mobile enquiry & £ বাংলা <img>'};assert.equal((await call('/api/chat/'+c.id,{token:c.token,body})).status,200);assert.equal((await call('/api/chat/'+c.id,{token:c.token,body})).status,200);let m=await (await call('/api/chat/'+c.id,{token:c.token})).json();assert.equal(m.messages.filter(x=>x.role==='visitor').length,1);assert.equal(m.messages[1].body,body.body);
assert.equal((await call('/api/chat-inbox/'+c.id,{token:c.token})).status,401);r=await call('/api/chat-inbox/'+c.id,{token:env.ADMIN_TOKEN,body:{id:crypto.randomUUID(),body:'Owner reply'}});assert.equal(r.status,200);m=await (await call('/api/chat/'+c.id,{token:c.token})).json();assert.equal(m.messages.at(-1).role,'owner');assert.equal(m.messages.at(-1).body,'Owner reply');assert.equal((await call('/api/chat/'+c.id,{token:c.token,body:{...body,body:'different'}})).status,409);
assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM nds_chat_alert_outbox').get().n,2);
assert.equal(sql.prepare('SELECT name FROM leads WHERE id=1').get().name,'preserved');assert.equal((await call('/api/chat/'+c.id,{token:c.token,body:{id:crypto.randomUUID(),body:'x'.repeat(1001)}})).status,400);
for(let i=0;i<10;i++)await call('/api/chat',{body:{name:'Rate test',enquiry:'This is a rate test'}});assert.equal((await call('/api/chat',{body:{name:'Rate test',enquiry:'This is a rate test'}})).status,429);
console.log('PASS durable SQL chat create, required fields, welcome, Unicode, visitor/owner authorization, owner reply readback, idempotent sends, origin restriction, message limits, creation rate limit, unchanged leads table');
