// Homepage presentation based on the owner-supplied 2026-09-28 visual reference.
// Leave the service templates and shared Worker behavior in their existing modules.
const HERO = `<section class="hero nds-concept-hero" aria-labelledby="nds-concept-title"><div class="wrap nds-concept-layout"><div class="nds-concept-copy"><span class="nds-concept-eyebrow">Digital solutions for a brighter business</span><h1 id="nds-concept-title">We Build Modern Websites That <em>Grow Your Business</em></h1><p class="nds-concept-subtitle">Professional web design, development, and digital solutions for businesses, brands, and startups.</p><p class="nds-concept-legacy">Build a stronger brand with design, technology and smart support.</p><p class="nds-concept-legacy">Neloy Digital Solutions helps businesses look professional, launch faster and manage digital work with confidence.</p><div class="nds-concept-actions"><a class="btn nds-concept-primary" href="#contact">Get a Free Quote <span aria-hidden="true">→</span></a><a class="btn nds-concept-secondary" href="/showcase">View Our Work</a></div><ul class="nds-concept-benefits" aria-label="Service highlights"><li>Fast Communication</li><li>Modern Design</li><li>Client Focused</li></ul></div><div class="nds-concept-visual" aria-label="Responsive website preview on laptop and phone" role="img"><div class="nds-concept-halo"></div><div class="nds-laptop"><div class="nds-laptop-screen"><div class="nds-demo-nav"><b><span>N</span> Neloy Digital Solutions</b><small>Home &nbsp; Services &nbsp; Work</small></div><div class="nds-demo-content"><span>CREATIVE DIGITAL SOLUTIONS</span><strong>Modern solutions.<br>Real results.</strong><span class="nds-demo-pill">Explore Our Work →</span></div><div class="nds-demo-art" aria-hidden="true"></div></div><div class="nds-laptop-base"></div></div><div class="nds-mobile-device"><div class="nds-mobile-screen"><div class="nds-mobile-brand"><b>N</b> Neloy</div><div class="nds-mobile-content"><span>DESIGN · WEB · GROWTH</span><strong>Modern<br>solutions.<br>Real results.</strong><i></i><small>Responsive by design</small></div></div></div></div></div></section>`;

const SHOWCASE = `<section class="nds-selected-work" aria-labelledby="nds-selected-work-title"><div class="wrap"><div class="nds-showcase-heading"><div><span class="nds-section-kicker">Our work</span><h2 id="nds-selected-work-title">Selected <em>Projects</em></h2><h2 class="nds-showcase-original">See the work. Meet the clients. Explore the results.</h2><p>Our completed projects and client testimonials now have their own dedicated page with a more creative visual experience.</p></div><a class="nds-outline-link" href="/showcase">View Portfolio &amp; Reviews →</a></div><div class="nds-work-grid"><a class="nds-work-card" href="/showcase#graphic-design-portfolio"><span class="nds-work-art nds-work-art-one"><span class="nds-art-monogram">N</span><span class="nds-art-lines"></span></span><span class="nds-work-label">Graphic Design Portfolio</span><span class="nds-work-type">Brand identity &amp; creative design</span></a><a class="nds-work-card" href="/showcase#web-design-projects"><span class="nds-work-art nds-work-art-two"><span class="nds-art-window"><i></i><b>Designed for clarity.</b><small>Web · Experience · Growth</small></span></span><span class="nds-work-label">Web Design Projects</span><span class="nds-work-type">Web design &amp; development</span></a></div></div></section>`;

const FEEDBACK = `<section class="nds-client-feedback" aria-labelledby="nds-feedback-title"><div class="wrap"><div class="nds-center-heading"><span class="nds-section-kicker">Client feedback</span><h2 id="nds-feedback-title">What Our <em>Clients Say</em></h2><p>Read more client stories in our portfolio.</p></div><div class="nds-feedback-grid"><blockquote><p>“I've enjoyed working with Neloy's team. They've been a great asset to me and my team. I'd recommend them if you're looking for affordable services.”</p><footer><strong>Nathan Webster</strong><span>Owner of NDUB BRAND</span></footer></blockquote><blockquote><p>“Neloy and his team are highly skilled creators and designers. They always create the best designs, and I really appreciate how much patience they have when it comes to revisions.”</p><footer><strong>Cynthia Gomez</strong><span>Owner of Simplicity Advertising</span></footer></blockquote></div><a class="nds-feedback-more" href="/showcase#testimonials">View All Client Testimonials →</a></div></section>`;

const PROCESS = `<section class="nds-concept-process" aria-labelledby="nds-process-title"><div class="wrap"><div class="nds-center-heading"><span class="nds-section-kicker">Our process</span><h2 id="nds-process-title">How <em>We Work</em></h2><p>A clear process built around your project requirements.</p></div><ol class="nds-process-steps"><li><span>01</span><strong>Discuss</strong><small>Tell us what you need and what matters to your business.</small></li><li><span>02</span><strong>Plan</strong><small>Agree on the scope, direction and budget.</small></li><li><span>03</span><strong>Create</strong><small>Review the work and share your feedback.</small></li><li><span>04</span><strong>Deliver</strong><small>Approve the final result for your project.</small></li></ol></div></section>`;

export function upgradeHomepage(html) {
  if (html.includes('id="nds-concept-title"')) return html;
  if (!html.includes('<section class="hero">') || !html.includes('<section class="showcaseTeaser">')) return html;
  html = html.replace(/<section class="hero">[\s\S]*?<\/section>/, HERO);
  // Move the existing published numbers without changing their values or text.
  const stats = html.match(/<section id="business-results"[\s\S]*?<\/section>/);
  if (stats) html = html.replace(stats[0], '').replace(HERO, HERO + stats[0]);
  html = html.replace(/<section class="showcaseTeaser">[\s\S]*?<\/section>/, SHOWCASE + FEEDBACK + PROCESS);
  return html;
}
